### ISSUE TITLE
Issue installing napari-stitcher

### ISSUE THREAD

**Issue by Eddymorphling** [multiview-stitcher/napari-stitcher#3]
Hi, I am trying to setup napari-stitcher. I already have a conda-env setup with multiview-stitcher and I get the below error when I pass `pip install https://github.com/multiview-stitcher/napari-stitcher`

Error message:

```
Collecting https://github.com/multiview-stitcher/napari-stitcher
  Downloading https://github.com/multiview-stitcher/napari-stitcher
     / 292.9 kB 887.2 kB/s 0:00:00
  ERROR: Cannot unpack file /tmp/pip-unpack-zrkutp1x/napari-stitcher (downloaded from /tmp/pip-req-build-lhg31zjo, content-type: text/html; charset=utf-8); cannot detect archive format
ERROR: Cannot determine archive format of /tmp/pip-req-build-lhg31zjo

```

**Comment by m-albert** [comment]
Hi @Eddymorphling, thanks for posting this issue!

I could reproduce your error and it made me realise that the syntax in the README for installing `napari-stitcher` from github is wrong. The correct syntax is:

`pip install "git+https://github.com/multiview-stitcher/napari-stitcher.git"`

**Comment by Eddymorphling** [comment]
@m-albert Thank you. How could I miss that? That fixed it :)

**Comment by m-albert** [comment]
Glad to hear :)
