### ISSUE TITLE
Register/Fuse buttons grayed out if one layer is not `Image`

### ISSUE THREAD

**Issue by jo-mueller** [multiview-stitcher/napari-stitcher#5]
Hi napari-stitcher devs,

first off: great plugin! We played around with it a bit today on some data to be stitched and found it really easy to use. One thing that seemed a bit odd to us: When selecting some layers and clicking on the `Selection` button in the merger widget, the `Fuse/Register` buttons remain grayed out if one of the selected layers is not of type `Image` (which obviously makes sense, because how would you merge, say, a points layer) - it's just that with many layers, it can be a bit hard to find which layer is the problematic one.

Maybe an easy solution for this would be to build a check into the function that adds the layers to the list and only adds them if the layer is of type `Image`.  [Here](https://github.com/multiview-stitcher/napari-stitcher/blob/e1b9483d6b23f86a01702b18ea8d129a678862e4/src/napari_stitcher/_stitcher_widget.py#L481) would probably be a good place.

cc @tsmejkal @zoccoler @maleehahassan

**Comment by m-albert** [comment]
Hey @jo-mueller, happy to hear you're liking the plugin and thanks a lot for the feedback!

> Maybe an easy solution for this would be to build a check into the function that adds the layers to the list and only adds them if the layer is of type Image.

I think it's a good idea to keep only labels in the selection that are available for fusion. In addition to image layers I'd also include label layers into this as 1) this currently works as labels are simply treated as images and 2) `multiview-stitcher` will add support for meaningfully fusing labels in the future. Would your use case include labels layers that should be filtered out?

Other than that there'd also be the option to load layers programmatically as
```python
import napari_stitcher
stitching_widget = napari_stitcher.StitcherQWidget(viewer)
viewer.window.add_dock_widget(stitching_widget)
stitching_widget.load_layers([l for l in viewer.layers if type(l) == napari.layers.image.image.Image])
```

> [Here](https://github.com/multiview-stitcher/napari-stitcher/blob/e1b9483d6b23f86a01702b18ea8d129a678862e4/src/napari_stitcher/_stitcher_widget.py#L481) would probably be a good place.

Yep agreed. Would you be willing to contribute a PR for this? Happy to otherwise do it on my side of course.

**Comment by jo-mueller** [comment]
I could try myself at it :)

One thing that occurred to me from looking at the code: It seems like the list of layers is iterated through in multiple places, i.e. [here](https://github.com/multiview-stitcher/napari-stitcher/blob/e1b9483d6b23f86a01702b18ea8d129a678862e4/src/napari_stitcher/_stitcher_widget.py#L481), [here](https://github.com/multiview-stitcher/napari-stitcher/blob/e1b9483d6b23f86a01702b18ea8d129a678862e4/src/napari_stitcher/_stitcher_widget.py#L552) and several other places. Filtering the list of layers at every place where this iteration is done would end up a bit clunky, I think.

Alternative solution: I could add a property `self.layers` to the widget, which would essentially be a view on the fitlered list of compatible layers. It would look something like this:

```python
@property
def layers(self):
  return [layer for layer in self.viewer.layers if isinstance(layer, (Image, Labels)]
```
