### ISSUE TITLE
Kernel crashes when fusing more than 200 images

### ISSUE THREAD

**Issue by tsmejkal** [multiview-stitcher/napari-stitcher#6]
Hey,

thanks a lot for sharing your stitching tool! I work together with @jo-mueller on a project and your tool comes in quite handy since I want to stitch about 830 images together. napari-stitcher works perfectly fine for about 200 images. With more images my kernel crashes.

I can build a workaround by fusing the images stepwise. Or maybe you have ideas what the problem might be?

The code snippet I use for fusing my images looks like this:

```
stitcher_widget = StitcherQWidget(viewer)
stitcher_widget.button_load_layers_all.clicked()
stitcher_widget.run_fusion()

napari.run()
```

**Comment by m-albert** [comment]
Hey @tsmejkal, thanks for your feedback 🙏

I don't think I ever tried the plugin with more than around 100 images 😁. But the idea is that it should work, so I'm happy you're on it :) Fusing images in several steps is a smart workaround.

I think there could be several reasons for why the kernel crashes:
1) the `multiview-stitcher` backend crashes when trying to handle your 800 input images. How large are your images? Are you loading them into RAM? If so, would you expect all images to fit into RAM together (including the fused one)?
2) the napari plugin `napari-stitcher` makes the kernel crash independently of the stitching backend. For example it registers some callbacks that could overwhelm the viewer when too many layers are loaded.

Is it an option for you to fuse your images without explicitly using the napari plugin? If so I'd recommend you to try using `multiview-stitcher` directly for fusing your images. Here's an example code showing how to script this: https://multiview-stitcher.github.io/multiview-stitcher/main/code_example/.

If this works, that'll be useful info to search for inefficiencies in the napari plugin. If it doesn't work, I'm actually right now working on an efficiency improvement of `multiview-stitcher` to be ready for use in the next days, which could also improve your usecase.

**Comment by tsmejkal** [comment]
Hey @m-albert,

thanks for pointing me to the multiview-stitcher. Without napari running in the back the whole process is much faster.

I tried it on my data and unfortunately I run into a problem again. The stitching and fusing process seems to work with 200 images most of the time (sometimes my kernel crashes again, same with fewer images). But when I then try to open the resulting image in napari, the kernel crashes almost always. In the few cases that it doesn't I get I real great fused image which kind of keeps me going to try and make it work ;)

I thought, okay, let's avoid the napari related kernel crash by directly exporting the fused_sim as a png-file instead. Then I get an error concerning the shape of fused_sim which I was not able to figure out by now. Could you maybe share an example code of how you handle exporting your images after fusing? I cannot make any sense of the array shape.

Concerning the size of the images:
The original images have shape=(1024, 1280), dtype=uint8, size in bytes=1310720
Before stitching and fusing I downscale them with factor 12 resulting in shape=(86, 107), dtype=uint8, size in bytes=9202

**Comment by m-albert** [comment]
Hey @tsmejkal

`fused_sim` as defined in the code example is an instance of [`xarray.DataArray`](https://docs.xarray.dev/en/stable/generated/xarray.DataArray.html) and you can get the shape of the attached array as such: `fused_sim.data.shape`.

Typically, the output of the fusion function has time and c dimensions which in your case might simply be dummy dimensions (e.g. the output could have a shape like `(1, 1, 1800, 1800)`.

In case the fused array fits into memory (it probably does if you have around 10-30 tiles of size ~(100,100) in each dimension), then you could first get a numpy array `fused_np = fused_sim.data.compute()` and then save it as a tif using `tifffile`, e.g. as `tifffile.imwrite('fused.tif', fused_np[0,0])`.

In case you your kernel crashes in the compute step above, you could currently try ``fused_np = fused_sim.data.compute(scheduler='single-threaded)` (it takes longer but might run through) or wait for the next multiview-stitcher release in some days which improves handling more tiles.

Please let me know if I can help further.

**Comment by tsmejkal** [comment]
Hey @m-albert 

thanks a lot for your input!

I solved my initial problem by creating a swapfile - or switching to a more powerful machine ;)
When looking at the RAM usage I see just a few peaks where more than my 14 GB RAM are needed. So using a swapfile for these short sequences doesn't slow done the calculation to much.

I am happy with this solution and thanks again for sharing your stitching tool. The image looks really good!

**Comment by m-albert** [comment]
Great that the stitching runs through for you now.


Thanks for sharing the observation that memory usage is peaking only shortly and that having a swap file solves it for you 👌

**Comment by m-albert** [comment]
@tsmejkal Quick update here: multiview-stitcher 0.1.14 (which napari-stitcher main depends on) significantly improves support for large data.

**Comment by tsmejkal** [comment]
Hi @m-albert ,
thanks for the update! I applied the new version of the multiview-stitcher to my data and it reduces the time for stitching by half. And the result looks even better. Seems like you changed something about the blending method as well. For me that means less ghosting and less sharp edges. And less waiting for the fused images ;)

That is amazing for me, so thanks a lot!

I also appreciate the loading progress bar of the fuse function :) Maybe there is a way to implement this nice feature into the compute function as well?

**Comment by m-albert** [comment]
Hey @tsmejkal, great to hear multiview-stitcher is working well for you, thanks a lot for the feedback :)

Indeed the blending changed. It'd be interesting to know whether you still get artifacts?

> I also appreciate the loading progress bar of the fuse function :) Maybe there is a way to implement this nice feature into the compute function as well?

For computations of dask arrays in general check out the very handy dask progress bar (works when using a local dask scheduler):

```python
from dask.diagnostics import ProgressBar

with ProgressBar():
    fused.data.compute()
```

**Comment by tsmejkal** [comment]
Hey @m-albert ,

Thanks for sharing the code snippet including the progress bar :)

Actually, due to some features of my dataset I am still working on improving the quality of the fused image. Artifacts that I see are still a bit of ghosting or - if I crop my images so that they overlap for only 30 px or less - some objects look as if they were cut. So e.g. only the lower half of a spheroid is visible in the fused image, while I can see the whole spheroid in the original image (the single tile I mean).

I have reached the limit of optimizing the quality of the fused image by adjusting the size of the overlap in my script. That might be good enough for my application. Still I was curious to try out some different blending options. From your code I assumed that the output_stack_mode attribute of the fuse function might be the place to look. I tried it today and I cannot see a difference between using 'sample' or the default here. 'intersection' throws me an error message (IndexError: invalid index to scalar variable.).
Is that the right place to switch blending modes or is this feature not implemented in the multiview-stitcher?

**Comment by m-albert** [comment]
Hey @tsmejkal,
> So e.g. only the lower half of a spheroid is visible in the fused image, while I can see the whole spheroid in the original image (the single tile I mean).

This suggests there are pairs of tiles for which the registration doesn't work well. Can you
- update your multiview-stitcher version and
- try explicitely setting a registration_binning of {'y': 1, 'x': 1} in registration.register?

This might help with registration accuracy.

> From your code I assumed that the output_stack_mode attribute of the fuse function might be the place to look

This option is more about determining the size of the output stack. Thanks for highlighting the error though.

> I also found the attribute blending_widths and added the corresponding data, but it doesn't seem to change the output fused image.

This determines the width of the transition between the tiles in the fused image. After updating to the newest multiview-stitcher version, you can set this e.g. as {'y': 10, 'x': 20} to observe its effect.

Let me know how it goes!
